class Location < ActiveRecord::Base
  has_many :places
  validates_presence_of :address, :latitude, :longitude

# Basic info on location based on places
  def resource_ids
    places.pluck(:resource_type).uniq
  end

  def resource_strings
    places.map { |p| p.resource_type }.uniq
  end

  def resources_count
    resource_types = resource_ids

    resource_types.map { |resource| places.where(resource_type: resource).inject(0){|sum, r| sum + r.resource_count}}
  end

  def others_count
    places.where(resource_type: 0).inject(0){|sum, r| sum + r.resource_count}
  end

  def weapons_count
    weapons_count = places.where(resource_type: 1).inject(0){|sum, r| sum + r.resource_count}

    weapons_count >= 30 ? 30 : weapons_count
  end

  def water_count
    water_count = places.where(resource_type: 2).inject(0){|sum, r| sum + r.resource_count}

    water_count >= 30 ? 30 : water_count
  end

  def food_count
    food_count = places.where(resource_type: 3).inject(0){|sum, r| sum + r.resource_count}

    food_count >= 20 ? 20 : food_count
  end

  def medicine_count
    medicine_count = places.where(resource_type: 4).inject(0){|sum, r| sum + r.resource_count}

    medicine_count >= 10 ? 10 : medicine_count
  end

  def tools_count
    tools_count = places.where(resource_type: 5).inject(0){|sum, r| sum + r.resource_count}

    tools_count >= 10 ? 10 : tools_count
  end

  def transportation_count
    transportation_count = places.where(resource_type: 6).inject(0){|sum, r| sum + r.resource_count}
  end

# GET/POST requests to external services

  # Makes an GET request to Data Science Toolkit and finds the population density in square kilometers for given coordinates
  def population_density
    url = "http://www.datasciencetoolkit.org/coordinates2statistics/" + latitude + "%2c" + longitude + "?statistics=population_density"

    resp = Faraday.get(url)
    body = JSON.parse(resp.body)

    return body[0]["statistics"]["population_density"]["value"]
  end

# Calculations
  def percent_survival
    # Average population density in square kilometers, via https://morrisseyweb.com/2012/03/09/the-average-us-population-density/
    # 275 most populous US cities average out to 3127 people per square mile. 3127 sq mi => 8098.8928 sq km
    average_population_density = 8098.8928;

    # Modifier based on your population density vs an average US city's population density
    # Percent modifier should be higher if your area is less dense and higher in denser areas
    # The logic is that you have a higher chance of encountering other zombies and having to compete with others for the same resources
    percent_modifier_based_on_density = average_population_density / population_density

    # Resource counts out of 100 points:
    #   Weapons max points = 30
    #   Water max points = 30
    #   Food max points = 20
    #   Medicine max points = 10
    #   Tools max points = 10
    #   Others and transportation are bonus points
    resources = [others_count, weapons_count, water_count, food_count, medicine_count, tools_count, transportation_count].sum / 100.0

    # Return survival percentage based on resources and modifier
    percent_modifier_based_on_density * resources
  end

  # Return true/false based on percent_survival. True if percent_survival is higher than random percent generated by #rand
  # It is possible for percent_survival for a location to be higher than 1 and therefore always true
  def survival?
    percent_survival > rand
  end
end
